# syntax=docker/dockerfile:1

FROM golang:1.13-alpine3.10 as builder

COPY . /web-pertemuan2
WORkDIR /web-pertemuan2

RUN apk add git build-base mysql-client && go mod download && go build -o main && chmod +x main

FROM alpine:latest

COPY --from=builder /web-pertemuan2/main /main
COPY views /views
COPY assets /assets
COPY controller /controller

ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/main"]
