name: gitleaks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - staging

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
15:14

Reply
Copy Selected Text
Copy Message Link
Pin
Forward
Select
Report
Delete

