# This is a basic workflow to help you get started with Actions
name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: zricethezav/gitleaks-action@v1
    - name: Gitleaks
