name: gitleaks

on:
  push:
    branches: [ main, staging ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, staging ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
