name: Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Publish Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        #uses: docker/login-action@v1
        #with:
        #  username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build . -t maduasli/vulnerability-goapp
          docker push maduasli/vulnerability-goapp:latest
      - name: Deploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ronald/web-example-golang
            ls -lah
            docker rm -f vulnapp-goapp && docker rmi maduasli/vulnerability-goapp:latest
            docker-compose up -d

